booking/urls.py
from django.conf.urls import url
from . import views

app_name = 'booking'

urlpatterns = [
    url(r'^$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^detail/book/(?P<amt>[0-9]+)/(?P<passengers>[0-9]+)/(?P<is_return>[a-zA-Z]+)$', views.book, name='book'),
    url(r'^status/$', views.status, name='status'),
]

railways/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^booking/', include('booking.urls')),
    url(r'^', include('booking.urls')),

]

booking/models.py
from django.db import models


class Log(models.Model):
    Email_id = models.CharField(max_length=100)
    Password = models.CharField(max_length=100)

    def __str__(self):
        return self.Email_id


class User(models.Model):
    Names = models.CharField(max_length=100)
    Email_id = models.CharField(max_length=100)
    Phone_no = models.CharField(max_length=100)
    DOB = models.CharField(max_length=20)


class Book(models.Model):
    Source = models.CharField(max_length=100)
    Destination = models.CharField(max_length=100)
    Train_Name = models.CharField(max_length=100)
    Date = models.CharField(max_length=100)
    CC_fare = models.CharField(max_length=100)
    Ac3_fare = models.CharField(max_length=100)
    Ac2_fare = models.CharField(max_length=100)
    Ac1_fare = models.CharField(max_length=100)
    Departure_time = models.CharField(max_length=100)
    Arrival_time = models.CharField(max_length=10)


class Bank(models.Model):
    Card_Number = models.CharField(max_length=16)
    Card_Holder = models.CharField(max_length=100)
    Expiry = models.CharField(max_length=20)
    CVV = models.CharField(max_length=3)

booking/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

booking/views.py
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from .models import Book, Bank


def index(request):
    return render(request, 'booking/index.html')


def detail(request):
    source = request.GET['p']
    destination = request.GET['q']
    date = request.GET['r']
    passengers = request.GET['s']
    try:
        is_return = request.GET['i']
    except:
        is_return = 'No'

    trains = get_list_or_404(Book, Source=source, Destination=destination, Date=date)

    return render(request, 'booking/detail.html', {'trains': trains, 'passengers': passengers, 'is_return': is_return})


def book(request, amt, passengers, is_return):
    return render(request, 'booking/book.html', {'amt': amt, 'passengers': passengers, 'is_return': is_return})


def status(request):
    card_number = request.GET['p']
    card_holder = request.GET['q']
    expiry = request.GET['r']
    cvv = request.GET['s']

    try:
        details = Bank.objects.get(Card_Holder=card_holder)
    except Bank.DoesNotExist:
        return HttpResponse('<h3>Payment Failed</h3>')

    if details.Card_Number == card_number and details.Expiry == expiry and details.CVV == cvv:
        return HttpResponse('<h3>Payment Successful</h3>')
    else:
        return HttpResponse('<h3>Payment Failed</h3>')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'booking/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'booking/index.html')
            else:
                return render(request, 'booking/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'booking/login.html', {'error_message': 'Invalid login'})
    return render(request, 'booking/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'booking/index.html')
    context = {
        "form": form,
    }
    return render(request, 'booking/register.html', context)

booking/templates/booking/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Log In{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'booking/styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

booking/templates/booking/book.html
{% extends 'booking/base.html' %}
{% block title %}Book-Confirmation{% endblock %}

{% block body %}
<div class="container-fluid vertical-align">

    <!--<div class="row">-->
    <div class="col-sm-6 col-sm-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Payment by card</h3>
                <h4><span>Signed In as {{ user.username }}, </span><a href="{% url 'booking:logout_user' %}">Logout</a></h4>
                <form class="form-horizontal" role="form" action="{% url 'booking:status' %}" method="get"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <br>

                    <label for="p">Card Number</label>
                    <input type="text" minlength="16" maxlength="16" class="form-control form-control-lg" name="p"
                           placeholder="Card Number" required>
                    <br>
                    <label for="q">Card Holder's Name</label>
                    <input type="text" class="form-control form-control-lg" name="q"
                           placeholder="Card holder's name" required>
                    <br>
                    <label for="r">Expiry</label>
                    <input type="text" class="form-control form-control-lg" name="r" required style="width:160px;">
                    <br>
                    <label for="s">CVV</label>
                    <input type="password" minlength="3" maxlength="3" class="form-control form-control-sm" name="s"
                           placeholder="CVV" required style="width:90px;">
                    <div class="form-row">
                        <center>
                            <div class="form-group">
                                <div class="col-sm-offset-1 col-sm-10">
                                    <br>
                                    <button type="submit" class="btn btn-success">
                                        {% ifequal is_return "No" %}
                                        <span>Proceed to pay Rs.{% widthratio amt 1 passengers %}</span>
                                        {% else %}
                                        <span>Proceed to pay Rs.{% widthratio amt 0.5 passengers %}</span>
                                        {% endifequal %}
                                    </button>
                                </div>
                            </div>
                        </center>
                    </div>
                    <span>Note: Once proceeded, the amount is non-refundable. In case of cancellation, suitable amount may be deduced before refund</span>
                </form>
            </div>
        </div>
    </div>
    <!-- </div>-->
</div>

{% endblock %}

booking/templates/booking/detail.html
{% extends 'booking/base.html' %}
{% block title %}Details{% endblock %}

{% block body %}
{% load staticfiles %}

<!--suppress ALL -->
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-group">
                <form method="get">
                    <li class="list-group-item">
                        <h2><strong>Trains</strong></h2>
                        <h4><span>Signed In as {{ user.username }}, </span><a href="{% url 'booking:logout_user' %}">Logout</a></h4>
                    </li>
                    <li class="list-group-item">
                        <table class="table">
                            <thead>
                            <tr style="background-color:black;color:white;">
                                <th>Source</th>
                                <th>Destination</th>
                                <th>Train Name</th>
                                <th>Date</th>
                                <th>Departure Time</th>
                                <th>Arrival Time</th>
                                <th>CC</th>
                                <th>AC 3</th>
                                <th>AC 2</th>
                                <th>AC 1</th>
                            </tr>
                            </thead>
                            {% for train in trains %}
                            <tr>
                                <td>{{ train.Source }}</td>
                                <td>{{ train.Destination }}</td>
                                <td>{{ train.Train_Name }}</td>
                                <td>{{ train.Date }}</td>
                                <td>{{ train.Departure_time }}</td>
                                <td>{{ train.Arrival_time }}</td>

                                {% ifequal is_return "No" %}
                                <td><span>{{ passengers }}x{{ train.CC_fare }} = </span><a
                                        href="book/{{ train.CC_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.CC_fare 1 passengers %}</span></a>
                                </td>
                                <td><span>{{ passengers }}x{{ train.Ac3_fare }} = </span><a
                                        href="book/{{ train.Ac3_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac3_fare 1 passengers %}</span></a>
                                </td>
                                <td><span>{{ passengers }}x{{ train.Ac2_fare }} = </span><a
                                        href="book/{{ train.Ac2_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac2_fare 1 passengers %}</span></a>
                                </td>
                                <td><span>{{ passengers }}x{{ train.Ac1_fare }} = </span><a
                                        href="book/{{ train.Ac1_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac1_fare 1 passengers %}</span></a>
                                </td>
                                {% else %}
                                <td><span>2x{{ passengers }}x{{ train.CC_fare }} = </span><a
                                        href="book/{{ train.CC_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.CC_fare 0.5 passengers %}</span></a>
                                </td>
                                <td><span>2x{{ passengers }}x{{ train.Ac3_fare }} = </span><a
                                        href="book/{{ train.Ac3_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac3_fare 0.5 passengers %}</span></a>
                                </td>
                                <td><span>2x{{ passengers }}x{{ train.Ac2_fare }} = </span><a
                                        href="book/{{ train.Ac2_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac2_fare 0.5 passengers %}</span></a>
                                </td>
                                <td><span>2x{{ passengers }}x{{ train.Ac1_fare }} = </span><a
                                        href="book/{{ train.Ac1_fare }}/{{ passengers }}/{{ is_return }}" type="submit"><span>&#x20b9;{% widthratio train.Ac1_fare 0.5 passengers %}</span></a>
                                </td>
                                {% endifequal %}
                            </tr>
                            {% endfor %}

                        </table>
                    </li>
                </form>
            </ul>
        </div>
    </div>

</div>

{% endblock %}

booking/templates/booking/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

booking/templates/booking/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Train</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'booking/styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body background="{% static 'booking/image/bg.png' %}">
<div class="container-fluid vertical-align">

    <!--<div class="row">-->
    <div class="col-sm-6 col-sm-offset-3 col-md-6 make-transparent">
        <div class="panel-body" style="color:white;">
            <h3>Train Booking</h3>
            <h4><span>Signed In as {{ user.username }}, </span><a href="{% url 'booking:logout_user' %}">Logout</a></h4>
            <form class="form-horizontal" role="form" action="{% url 'booking:detail' %}" method="get"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <br>

                <label for="p">Source</label>
                <input type="text" class="form-control form-control-lg" name="p"
                       placeholder="Source" required>
                <br>
                <label for="q">Destination</label>
                <input type="text" class="form-control form-control-lg" name="q"
                       placeholder="Destination" required>
                <br>
                <label for="r">Date</label>
                <input type="text" class="form-control form-control-lg" name="r"
                       placeholder="Date" required>
                <br>
                <label for="s">Passengers</label>
                <input type="number" min="1" class="form-control form-control-sm" name="s" maxlength="3" value="1"
                       placeholder="Number of passengers" required>
                <br>
                <label for="i">Return Journey</label>
                <input type="checkbox" value="return" id="is_return" name="i">
                <br>
                <div class="form-row">
                    <center>
                        <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-10">
                                <br>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </center>
                </div>
            </form>
        </div>
    </div>
    <!-- </div>-->
</div>
</body>
</html>

booking/templates/booking/login.html
{% extends 'booking/base.html' %}
{% block title %}Log In{% endblock %}

{% block body %}
<div class="container-fluid vertical-align">

    <div class="col-sm-6 col-sm-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Log In</h3>
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" role="form" action="{% url 'booking:login_user'%}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id_username">
                            Username:
                        </label>
                        <div class="col-sm-10">
                            <input id="id_username" maxlength="30" name="username" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id_password">
                            Password:
                        </label>
                        <div class="col-sm-10">
                            <input id="id_password" maxlength="30" name="password" type="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                Don't have an account? <a href="{% url 'booking:register' %}">Click here</a> to register.
            </div>
        </div>
    </div>
</div>


{% endblock %}

booking/templates/booking/register.html
{% extends 'booking/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid vertical-align">
    <div class="col-sm-6 col-sm-offset-3 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Register for an Account</h3>
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'booking/form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                Already have an account? <a href="{% url 'booking:login_user' %}">Click here</a> to log in.
            </div>
        </div>
    </div>
</div>


{% endblock %}